### ISSUE TITLE
Compression broken

### ISSUE THREAD

**Issue by tballard** [com-lihaoyi/requests-scala#107]
POSTing compressed data fails. For a small file, examining the bytes actually received reveals them to be  "31,139,8,0,0,0,0,0,0,0,-1". The 31,139 means gzip, the -1 is end of file, the rest I suspect means "I forgot to close/finish the GZIPOutputStream.  Looking for the code in requests/Requester.scala there is a section that I suspect should be changed to something like the following. Admittedly I haven't gotten my Ammonite script to use it, yet, but I'd be surprised if isn't the issue.  I notice there are tests for the compression modes but they clearly proved insufficient.

```
if (!chunkedUpload) {
            val bytes = new ByteArrayOutputStream()
            val os = compress.wrap(connection.getOutputStream)
            data.write(os)
            os.close()
            val byteArray = bytes.toByteArray
            connection.setFixedLengthStreamingMode(byteArray.length)
            if (byteArray.nonEmpty) connection.getOutputStream.write(byteArray)
          } else {
            connection.setChunkedStreamingMode(0)
            val os = compress.wrap(connection.getOutputStream)
            data.write(os)
            os.close()
          }
}
```

**Comment by daddykotex** [comment]
I saw a similar issue use requests-scala from `mill` 0.10 but the issue disappeared when I upgrade to 0.11.

I assume there was a fix in here not too long ago, or in `geny` that solved it. I would think that you can close this

**Comment by lihaoyi** [comment]
Fixed by https://github.com/com-lihaoyi/requests-scala/pull/108
