### ISSUE TITLE
Client Side Certificates

### ISSUE THREAD

**Issue by gorros** [com-lihaoyi/requests-scala#12]
Are you planning to add support for client-side certificates similar to [requests](http://docs.python-requests.org/en/master/user/advanced/#client-side-certificates)? 
From my experience, the current Java API is very ugly and painful :)

**Comment by lihaoyi** [comment]
feel free to send a PR!

**Comment by gorros** [comment]
I am not sure if there is a nice way to do it without dealing with truststore and keystore.

**Comment by Hakky54** [comment]
As an additional to pullrequest https://github.com/lihaoyi/requests-scala/pull/48 There is also now support for a custom sslcontext within the following already merged pullrequest https://github.com/lihaoyi/requests-scala/pull/62

**Comment by Magua** [comment]
This can be closed implemented in PR #48
