### ISSUE TITLE
feature request: dynamic HTTP method - requests.send(url, method="GET")

### ISSUE THREAD

**Issue by bellam** [com-lihaoyi/requests-scala#67]
There are a lot of cases where the HTTP method (GET, POST etc) needs to be dynamic, especially in scripts. This would be a good feature to have. 

Something like `requests.send(url, method="GET")`

For example, in javascript's fetch, there's
`await fetch('/article/user/update', { method: 'POST',`
or
in jquery, there's
`$.ajax({ url: "/article/post/get", method: 'POST',`

**Comment by lihaoyi** [comment]
This can be done via 

```scala
requests.Requester("GET", requests.Session()).apply("https://www.google.com")
```
