### ISSUE TITLE
Clarify timeouts unit

### ISSUE THREAD

**Issue by patrykcelinski** [com-lihaoyi/requests-scala#85]
I'm confused about the time unit in timeouts.

Apparently, in python, these are seconds.

```py
r = requests.get(w, verify=False, timeout=10) # 10 seconds
```

I used in my config `FiniteDuration` and then `readTimeout = config.readTimeout.toSeconds.toInt` and it turned out that all requests are failing. 

Looking at the README of requests-scala I think that it is using milliseconds:

```scala
requests.get("https://httpbin.org/delay/1", readTimeout = 10)
// TimeoutException

requests.get("https://httpbin.org/delay/1", readTimeout = 1500)
// ok
```

**Comment by lihaoyi** [comment]
Gonna call this done in https://github.com/com-lihaoyi/requests-scala/commit/9be5284d55ae1ff60b285554c579fdd8c0fcb076
